tunnel: 9aab098a-df26-4b67-bb40-ae2c4b8bc32c
credentials-file: C:\Users\HP\.cloudflared\9aab098a-df26-4b67-bb40-ae2c4b8bc32c.json
ingress:
  - hostname: voice.praanav.in
    service: http://localhost:3001
  - service: http_status:404 